# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 14:32
from __future__ import unicode_literals

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('rank', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('appointment_type', models.CharField(choices=[('academic', 'Academic'), ('professional', 'Professional Practice'), ('research', 'Research')], default='academic', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=20, null=True)),
                ('address', address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(blank=True, max_length=30, null=True)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('suffix', models.CharField(blank=True, max_length=30, null=True)),
                ('credentials', models.CharField(blank=True, max_length=30, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('address', address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Parent'), (2, 'Agreement')])),
                ('from_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_organizations', to='people.Organization')),
                ('to_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_organizations', to='people.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='relationships',
            field=models.ManyToManyField(related_name='related_to', through='people.Relationship', to='people.Organization'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='people.Organization'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='incumbent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incumbent', to='people.Person'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='people.Organization'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to='people.Person'),
        ),
    ]
