# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('license_name', models.CharField(blank=True, max_length=200, null=True)),
                ('license_id', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licensing_department', to='people.Organization')),
                ('licensee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licensee', to='people.Person')),
                ('licensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licensor', to='people.Organization')),
            ],
        ),
    ]
