# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='license_abbreviation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
