# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20170305_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('honor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('honor_abbreviation', models.CharField(blank=True, max_length=20, null=True)),
                ('honor_id', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='honoring_department', to='people.Organization')),
                ('honoree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honoree', to='people.Person')),
                ('honoror', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='honoror', to='people.Organization')),
            ],
        ),
    ]
