# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_license_license_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licensing_department', to='people.Organization'),
        ),
    ]
